version: 2

builds:
  - id: devinfra
    main: .
    binary: devinfra
    ldflags:
      - -s -w
      - -X github.com/heysarver/devinfra/internal/version.Version={{.Version}}
      - -X github.com/heysarver/devinfra/internal/version.Commit={{.ShortCommit}}
      - -X github.com/heysarver/devinfra/internal/version.Date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

  - id: di
    main: .
    binary: di
    ldflags:
      - -s -w
      - -X github.com/heysarver/devinfra/internal/version.Version={{.Version}}
      - -X github.com/heysarver/devinfra/internal/version.Commit={{.ShortCommit}}
      - -X github.com/heysarver/devinfra/internal/version.Date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: devinfra
    builds:
      - devinfra
      - di
    format: tar.gz
    name_template: "devinfra_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: devinfra
    ids:
      - devinfra
    repository:
      owner: heysarver
      name: homebrew-tap
    homepage: https://github.com/heysarver/devinfra
    description: Local development infrastructure manager
    license: MIT
    install: |
      bin.install "devinfra"
      bin.install_symlink "devinfra" => "di"
    test: |
      assert_match version.to_s, shell_output("#{bin}/devinfra version")
