version: 2

builds:
  - id: devinfra
    main: .
    binary: devinfra
    ldflags:
      - -s -w
      - -X github.com/heysarver/devinfra/internal/version.Version={{.Version}}
      - -X github.com/heysarver/devinfra/internal/version.Commit={{.ShortCommit}}
      - -X github.com/heysarver/devinfra/internal/version.Date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: devinfra
    ids:
      - devinfra
    formats:
      - tar.gz
    name_template: "devinfra_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
