package project

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/heysarver/devinfra/internal/compose"
	"github.com/heysarver/devinfra/internal/config"
	"github.com/heysarver/devinfra/internal/ui"
)

// AddOpts contains the parameters for importing an existing project.
type AddOpts struct {
	Name        string
	Dir         string
	Services    []config.Service
	ComposeFile string // detected compose filename (e.g., "compose.yaml")
	Cloned      bool   // true if we cloned the directory (safe to remove on rollback)
}

// Add imports an existing project into devinfra management.
func Add(ctx context.Context, opts AddOpts) error {
	if err := config.EnsureDirs(); err != nil {
		return fmt.Errorf("creating config directories: %w", err)
	}

	rb := &rollback{}
	defer func() { rb.execute() }()

	dir := opts.Dir

	// If we cloned this directory, it's safe to remove on rollback
	if opts.Cloned {
		rb.add(func() error { return os.RemoveAll(dir) })
	}

	// Generate overlay if services were selected
	if len(opts.Services) > 0 {
		ui.Info("Generating docker-compose.devinfra.yaml...")
		if err := generateOverlay(opts.Name, dir, opts.Services); err != nil {
			return fmt.Errorf("generating overlay: %w", err)
		}
		rb.add(func() error {
			_ = os.Remove(filepath.Join(dir, "docker-compose.devinfra.yaml"))
			return nil
		})

		ui.Info("Consider adding docker-compose.devinfra.yaml to your .gitignore")
	}

	// Generate certs
	if err := compose.GenerateCerts(ctx, opts.Name); err != nil {
		return fmt.Errorf("generating certs: %w", err)
	}
	rb.add(func() error {
		_ = compose.RemoveCerts(opts.Name)
		return nil
	})

	// Register in projects.yaml
	ui.Info("Registering project...")
	reg, err := config.LoadRegistry()
	if err != nil {
		return fmt.Errorf("loading registry: %w", err)
	}

	project := config.Project{
		Name:        opts.Name,
		Dir:         dir,
		Domain:      fmt.Sprintf("*.%s.test", opts.Name),
		Services:    opts.Services,
		ComposeFile: opts.ComposeFile,
		Created:     time.Now().Format("2006-01-02"),
	}

	if err := reg.Add(project); err != nil {
		return err
	}
	if err := config.SaveRegistry(reg); err != nil {
		return fmt.Errorf("saving registry: %w", err)
	}
	rb.add(func() error {
		reg, _ := config.LoadRegistry()
		if reg != nil {
			_ = reg.Remove(opts.Name)
			_ = config.SaveRegistry(reg)
		}
		return nil
	})

	// Success — disarm rollback
	rb.disarm()

	ui.Ok("Project '%s' registered!", opts.Name)
	fmt.Fprintln(os.Stderr)
	fmt.Fprintf(os.Stderr, "  Directory:  %s\n", dir)
	if len(opts.Services) > 0 {
		fmt.Fprintln(os.Stderr, "  URLs:")
		for i, svc := range opts.Services {
			if i == 0 {
				fmt.Fprintf(os.Stderr, "    https://%s.test\n", opts.Name)
			}
			fmt.Fprintf(os.Stderr, "    https://%s.%s.test\n", svc.Name, opts.Name)
		}
	}
	fmt.Fprintf(os.Stderr, "  Dashboard:  https://traefik.test\n")
	fmt.Fprintln(os.Stderr)
	fmt.Fprintln(os.Stderr, "Next steps:")
	fmt.Fprintf(os.Stderr, "  di up %s\n", opts.Name)

	return nil
}

// generateOverlay creates a docker-compose.devinfra.yaml with Traefik labels and networks.
func generateOverlay(name, dir string, services []config.Service) error {
	var b strings.Builder

	b.WriteString("# Generated by devinfra — do not edit manually\n")
	b.WriteString("services:\n")
	for i, svc := range services {
		routerName := fmt.Sprintf("%s-%s", name, svc.Name)

		var rule string
		if i == 0 {
			rule = fmt.Sprintf("Host(`%s.test`) || Host(`%s.%s.test`)", name, svc.Name, name)
		} else {
			rule = fmt.Sprintf("Host(`%s.%s.test`)", svc.Name, name)
		}

		b.WriteString(fmt.Sprintf("  %s:\n", svc.Name))
		b.WriteString("    networks:\n")
		b.WriteString("      - traefik\n")
		b.WriteString("    labels:\n")
		b.WriteString("      - \"traefik.enable=true\"\n")
		b.WriteString(fmt.Sprintf("      - \"traefik.http.routers.%s.rule=%s\"\n", routerName, rule))
		b.WriteString(fmt.Sprintf("      - \"traefik.http.routers.%s.entrypoints=websecure\"\n", routerName))
		b.WriteString(fmt.Sprintf("      - \"traefik.http.routers.%s.tls=true\"\n", routerName))
		b.WriteString(fmt.Sprintf("      - \"traefik.http.services.%s.loadbalancer.server.port=%d\"\n", routerName, svc.Port))
		b.WriteString("      - \"traefik.docker.network=traefik\"\n")
		b.WriteString("\n")
	}

	b.WriteString("networks:\n")
	b.WriteString("  traefik:\n")
	b.WriteString("    external: true\n")

	return os.WriteFile(filepath.Join(dir, "docker-compose.devinfra.yaml"), []byte(b.String()), 0644)
}
